---
services:
  webhook:
    image: ghcr.io/project-meent/webhook:v0.5.4
    ports:
      - 127.0.0.1:9083:80
    volumes:
      - ./config.php:/app/config.php
      - ./data/api:/app/data/api
      - ./data/solid-client:/app/data/solid-client

  change-webhook:
    image: ghcr.io/project-meent/webhook:v0.5.4
    volumes:
      - ./config.php:/app/config.php
      - ./data/api:/app/data/api
      - ./data/solid-client:/app/data/solid-client
    command: sh -c "chown -R www-data:www-data /app/config.php /app/data/api/ /app/data/solid-client/;"
    depends_on:
      - webhook
