    LogFormat "%v %V:%p %h %l %u [%{%d/%b/%Y:%T}t.%{msec_frac}t %{%z}t] \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-Forwarded-For}i\" %I %O %X %D (%{ratio}n%%) \"%{SSL_PROTOCOL}x\"" cvhost_combined_global

GlobalLog ${APACHE_LOG_DIR}/access.log cvhost_combined_global

<VirtualHost *:443>
	ServerName webhook.energiemeent.nl

	DocumentRoot /app/web

	SSLEngine on
	SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
	SSLCertificateKeyFile   /etc/ssl/private/ssl-cert-snakeoil.key

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	<Directory />
		Require all granted
		RewriteEngine On
		RewriteBase /
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteRule ^(.+)$ index.php [QSA,L]
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName webhook.energiemeent.nl

	DocumentRoot /app/web

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	<Directory />
		Require all granted
		RewriteEngine On
		RewriteBase /
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteRule ^(.+)$ index.php [QSA,L]
	</Directory>
</VirtualHost>
